# Generated by Django 4.1.6 on 2023-02-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_guild', models.CharField(max_length=255)),
                ('desc_guild', models.TextField()),
                ('icon_guild', models.CharField(max_length=255)),
                ('region_guild', models.CharField(max_length=255)),
                ('owner_guild', models.CharField(max_length=255)),
                ('membercount_guild', models.IntegerField()),
                ('createdat_guild', models.DateField()),
            ],
        ),
    ]
