# Generated by Django 4.1.6 on 2023-02-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id_channel', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_channel', models.CharField(max_length=255)),
                ('type_channel', models.CharField(max_length=255)),
                ('createdat_channel', models.DateField()),
                ('position_channel', models.IntegerField()),
                ('id_guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.server')),
            ],
        ),
    ]
