# Generated by Django 4.1.6 on 2023-02-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_member', models.CharField(max_length=255)),
                ('nick_member', models.CharField(max_length=255)),
                ('avatar_member', models.CharField(max_length=255)),
                ('banner_member', models.CharField(max_length=255)),
                ('joinedat_member', models.DateField()),
                ('id_guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.server')),
            ],
        ),
    ]
