# Generated by Django 4.1.6 on 2023-02-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.member')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_role', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_role', models.CharField(max_length=255)),
                ('position_role', models.IntegerField()),
                ('members', models.ManyToManyField(through='tracker.MemberRole', to='tracker.member')),
            ],
        ),
        migrations.AddField(
            model_name='memberrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.roles'),
        ),
    ]
