# Generated by Django 4.1.6 on 2023-03-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_memberrole_roles_memberrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_message', models.TextField()),
                ('date_message', models.DateField()),
                ('id_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.channel')),
                ('id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.member')),
            ],
        ),
    ]
