# Generated by Django 4.1.6 on 2023-09-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('name_event', models.CharField(blank=True, max_length=255, null=True)),
                ('date_event', models.DateField()),
                ('start_event', models.TimeField()),
                ('end_event', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.member')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='members_event',
            field=models.ManyToManyField(through='tracker.MemberEvent', to='tracker.member'),
        ),
    ]
