# Generated by Django 4.1.6 on 2023-09-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_event_memberevent_event_members_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_event',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
