# Generated by Django 4.2.5 on 2023-10-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_event_date_event_alter_event_end_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='Offline', max_length=20),
        ),
    ]
